apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
      - name: nodejs
        image: "jinalpadhiar15@gmail.com/e-commerce-api-app:latest"
        ports:
        - containerPort: 8080
        env:
        - name: MONGO_URL
          value: "mongodb://127.0.0.1:27017/"
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
spec:
  selector:
    app: nodejs
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer
